# Generated by Django 6.1 on 2026-09-08 16:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('main', '0048_delete_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('url', models.URLField(blank=True, default=' ', max_length=255)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, default=' ', max_length=255, unique=True)),
                ('postitive_small_integer', models.PositiveSmallIntegerField(blank=True, default=' ', null=True)),
                ('postitive_integer', models.PositiveIntegerField(blank=True, default=' ', null=True)),
                ('postitive_big_integer', models.PositiveBigIntegerField(blank=True, default=' ', null=True)),
                ('generic_ipaddress', models.GenericIPAddressField(blank=True, default=' ', null=True)),
                ('integer', models.IntegerField(blank=True, default=0)),
                ('photo', models.ImageField(blank=True, default=' ', upload_to='')),
                ('destination_price', models.FloatField(blank=True, default=' ')),
                ('email', models.EmailField(blank=True, default=' ', max_length=255, unique=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hash', models.BinaryField(blank=True)),
                ('name_hi', models.CharField(blank=True, default=' ', max_length=255)),
                ('name_en', models.CharField(blank=True, default=' ', max_length=255)),
                ('address_hi', models.CharField(blank=True, default=' ', max_length=255)),
                ('address_en', models.TextField(blank=True, default=' ')),
                ('contact', models.CharField(blank=True, default=' ', max_length=255)),
                ('areas_available', models.CharField(blank=True, default=' ', max_length=255)),
                ('menus', models.FileField(blank=True, default=' ', upload_to='')),
                ('gallery', models.JSONField(blank=True, default=dict)),
                ('description_hi', models.TextField(blank=True, default=' ')),
                ('description_en', models.TextField(blank=True, default=' ')),
                ('rooms', models.IntegerField(blank=True, default=0)),
                ('hotel_area', models.CharField(blank=True, default=' ', max_length=255)),
                ('garden_area', models.CharField(blank=True, default=' ', max_length=255)),
                ('parking', models.BooleanField(blank=True, default=' ')),
                ('room_price', models.IntegerField(blank=True, default=' ', null=True)),
                ('garden_rate', models.IntegerField(blank=True, default=' ', null=True)),
                ('verify_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255)),
                ('mobile', models.BigIntegerField(blank=True, default=' ', unique=True)),
                ('documents', models.FilePathField(blank=True, path='/srijan/images')),
                ('tags', models.CharField(blank=True, choices=[('Samarth', 'Samarth/समर्थ'), ('Saksham', 'Saksham/सक्षम'), ('Samridhh', 'Samridhh/समृद्ध')], default='General', max_length=255)),
                ('tehsil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tehsil')),
            ],
            options={
                'db_table': 'events_venues',
            },
        ),
    ]
