# Generated by Django 6.1 on 2026-08-25 07:52

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hi', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'jobs_recruitment_category',
            },
        ),
        migrations.CreateModel(
            name='Jobslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=100)),
                ('jobtype', models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=50, null=True)),
                ('posts', models.PositiveIntegerField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=512, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcreatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=64)),
                ('name_hi', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.recruitmentcategory')),
            ],
            options={
                'db_table': 'jobs_recruitments',
            },
        ),
    ]
