# Generated by Django 6.1 on 2026-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_newslist_created_by_newslist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
