# Generated by Django 6.1 on 2026-09-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
