# Generated by Django 6.1 on 2026-09-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_category_itemlist_created_by_itemlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
