# Generated by Django 6.1 on 2026-09-01 08:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_alter_itemlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
