# Generated by Django 6.1 on 2026-09-01 18:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_alter_itemlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
