# Generated by Django 6.1 on 2026-09-01 19:06

import tinymce_4.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0005_alter_itemlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='description',
            field=tinymce_4.fields.TinyMCEModelField(verbose_name='Foo content'),
        ),
    ]
