# Generated by Django 6.1 on 2026-09-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0002_category_bookbanklist_author_bookbanklist_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbanklist',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookbank.category'),
            preserve_default=False,
        ),
    ]
