# Generated by Django 6.1 on 2026-09-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0003_bookbanklist_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssueReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstatus', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=10)),
                ('issuedate', models.DateTimeField(auto_now=True)),
                ('borrowdate', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bookbank.bookbanklist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('takenby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takenby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
