# Generated by Django 6.1 on 2026-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0004_bookissuereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissuereturn',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
