# Generated by Django 6.1 on 2026-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0005_bookissuereturn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuereturn',
            name='borrowdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookissuereturn',
            name='issuedate',
            field=models.DateTimeField(),
        ),
    ]
