# Generated by Django 6.1 on 2026-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0006_alter_bookissuereturn_borrowdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuereturn',
            name='borrowdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookissuereturn',
            name='issuedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
