# Generated by Django 6.1 on 2026-09-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0007_alter_bookissuereturn_borrowdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissuereturn',
            old_name='borrowdate',
            new_name='returndate',
        ),
    ]
