# Generated by Django 6.1 on 2026-09-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_propertylist_created_by_alter_propertylist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='type',
            field=models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Plot', 'Plot'), ('Shop', 'Shop')], default=2),
            preserve_default=False,
        ),
    ]
