# Generated by Django 6.1 on 2026-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_propertylist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Flat', 'Flat'), ('Plot', 'Plot'), ('Shop', 'Shop')], null=True),
        ),
    ]
