# Generated by Django 6.1 on 2026-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_propertylist_area_propertylist_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylist',
            old_name='type',
            new_name='ptype',
        ),
        migrations.AddField(
            model_name='propertylist',
            name='configs',
            field=models.CharField(blank=True, choices=[('Park', 'Park'), ('Car Parking', 'Car Parking'), ('Gated Community', 'Gated Community'), ('Security Cabin', 'Security Cabin')], null=True),
        ),
    ]
