# Generated by Django 6.1 on 2026-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_alter_propertylist_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='configs',
            field=models.CharField(blank=True, choices=[('Park', 'Park'), ('Car Parking', 'Car Parking'), ('Gated Community', 'Gated Community'), ('Security Cabin', 'Security Cabin')], null=True),
        ),
    ]
