# Generated by Django 6.1 on 2026-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_alter_propertylist_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='configs',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], null=True),
        ),
    ]
