# Generated by Django 6.1 on 2026-09-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0009_alter_propertylist_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='configs',
            field=models.CharField(blank=True, null=True),
        ),
    ]
