# Generated by Django 6.1 on 2026-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0010_alter_propertylist_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='balconies',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='ptype',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Independent House', 'Independent House'), ('Independent Floor', 'Independent Floor'), ('Plot ', 'Plot '), ('Studio', 'Studio'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse'), ('Villa', 'Villa'), ('Agriculture Land', 'Agriculture Land')], null=True),
        ),
    ]
