# Generated by Django 6.1 on 2026-09-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0011_propertylist_balconies_propertylist_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='furnishing_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='ptype',
            field=models.CharField(blank=True, null=True),
        ),
    ]
