# Generated by Django 6.1 on 2026-09-10 17:04

import tinymce_4.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_bloglist_created_by_alter_bloglist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='description',
            field=tinymce_4.fields.TinyMCEModelField(default=2, verbose_name='Foo content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloglist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='bloglist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
