# Generated by Django 6.1 on 2026-09-11 10:18

import editor101.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_bloglist_description_bloglist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=editor101.fields.RichTextField(verbose_name='Foo content'),
        ),
    ]
