# Generated by Django 6.1 on 2026-09-11 10:40

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
