# Generated by Django 6.1 on 2026-09-11 10:52

import trix.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=trix.fields.TrixField(verbose_name='Content'),
        ),
    ]
