# Generated by Django 6.1 on 2026-09-11 11:17

import chedito.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=chedito.fields.RichTextField(),
        ),
    ]
