# Generated by Django 6.1 on 2026-09-11 11:20

import chedito.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=chedito.fields.RichTextField(quill_config={'modules': {'toolbar': ['bold', 'italic', 'link']}}),
        ),
    ]
