# Generated by Django 6.1 on 2026-09-11 13:29

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=prose.fields.RichTextField(),
        ),
    ]
