# Generated by Django 6.1 on 2026-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
