# Generated by Django 6.1 on 2026-09-11 14:33

import textedit.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_bloglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='description',
            field=textedit.models.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
