# Generated by Django 6.1 on 2026-09-11 14:47

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_bloglist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='description',
        ),
        migrations.AddField(
            model_name='bloglist',
            name='body',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloglist',
            name='body_text',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
