# Generated by Django 6.1 on 2026-09-11 15:07

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_remove_bloglist_description_bloglist_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='body',
        ),
        migrations.RemoveField(
            model_name='bloglist',
            name='body_text',
        ),
        migrations.AddField(
            model_name='bloglist',
            name='description',
            field=froala_editor.fields.FroalaField(default=2),
            preserve_default=False,
        ),
    ]
