# Generated by Django 6.1 on 2026-09-11 15:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_remove_bloglist_body_remove_bloglist_body_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglist',
            name='description',
        ),
        migrations.AddField(
            model_name='bloglist',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=2, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
