# Generated by Django 6.1 on 2026-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_bloglist_description_bloglist_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
