# Generated by Django 6.0 on 2026-04-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
    ]
