# Generated by Django 6.0 on 2026-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_classsection_sample_created_at_sample_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslist',
            name='posts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobslist',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
