# Generated by Django 6.0 on 2026-05-06 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_jobslist_posts_alter_jobslist_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
