# Generated by Django 6.0 on 2026-05-07 15:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_jobslist_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslist',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
