# Generated by Django 6.0 on 2026-05-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_jobslist_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobslist',
            old_name='type',
            new_name='jobtype',
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='joining_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=512, null=True)),
                ('established_year', models.DateField(blank=True, null=True)),
                ('principal_name', models.CharField(max_length=100)),
                ('board', models.CharField(blank=True, choices=[('RBSE', 'RBSE'), ('CBSE', 'CBSE')], default='RBSE', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
