# Generated by Django 6.0 on 2026-05-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_student_adminssion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('first', models.SmallIntegerField(blank=True, null=True)),
                ('second', models.SmallIntegerField(blank=True, null=True)),
                ('third', models.SmallIntegerField(blank=True, null=True)),
                ('total', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classname', models.ManyToManyField(related_name='myclassename', to='accounts.classsection')),
                ('subject', models.ManyToManyField(related_name='marksubjects', to='accounts.subject')),
            ],
        ),
    ]
