# Generated by Django 6.0 on 2026-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_subjectmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='total',
            field=models.SmallIntegerField(blank=True, default='calculate_total', null=True),
        ),
    ]
