# Generated by Django 6.1 on 2026-08-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_accounttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='jobslist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobslist',
            name='tehsil',
        ),
        migrations.RemoveField(
            model_name='school',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='child',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectmark',
            name='child',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='child',
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.DeleteModel(
            name='Jobslist',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectMark',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
