# Generated by Django 6.0 on 2026-04-05 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_serviceprovider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 5, 16, 43, 6, 966212, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
