# Generated by Django 6.0 on 2026-04-06 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_serviceprovider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 6, 13, 58, 29, 791007, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[(0, 'New'), (1, 'Active'), (2, 'Inactive')], default='0'),
        ),
    ]
