# Generated by Django 6.0 on 2026-04-06 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_serviceprovider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 6, 14, 35, 33, 488197, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted'), ('Marked', 'Marked')], default='New'),
        ),
    ]
