# Generated by Django 6.0 on 2026-04-09 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_serviceprovider_details_serviceprovider_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 9, 15, 20, 56, 208391, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
