# Generated by Django 6.0 on 2026-04-09 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 9, 15, 27, 2, 566351, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
