# Generated by Django 6.0 on 2026-04-14 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 14, 16, 36, 4, 291942, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
