# Generated by Django 6.0 on 2026-04-22 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 22, 8, 41, 31, 450299, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
