# Generated by Django 6.0 on 2026-04-25 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 25, 14, 2, 55, 49767, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
