# Generated by Django 6.0 on 2026-04-26 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 26, 16, 33, 34, 5080, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
