# Generated by Django 6.0 on 2026-04-27 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 4, 27, 13, 57, 3, 31857, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
