# Generated by Django 6.0 on 2026-05-06 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 6, 16, 43, 23, 893888, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
