# Generated by Django 6.0 on 2026-05-16 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 16, 17, 26, 10, 70557, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
