# Generated by Django 6.0 on 2026-05-17 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 17, 16, 6, 33, 984291, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
