# Generated by Django 6.1 on 2026-08-23 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 8, 23, 14, 4, 26, 747456, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
