# Generated by Django 6.1 on 2026-08-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='category',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='many_to_many',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
        migrations.DeleteModel(
            name='LssemsService',
        ),
        migrations.DeleteModel(
            name='Recruitment',
        ),
        migrations.DeleteModel(
            name='RecruitmentCategory',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.DeleteModel(
            name='SchemeCategory',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
