# Generated by Django 6.1 on 2026-09-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_delete_accounttype_remove_serviceprovider_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utility',
        ),
        migrations.DeleteModel(
            name='UtilityCategory',
        ),
    ]
