# Generated by Django 6.1 on 2026-09-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_delete_utility_delete_utilitycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
