# Generated by Django 6.1 on 2026-08-26 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=512, null=True)),
                ('established_year', models.DateField(blank=True, null=True)),
                ('principal_name', models.CharField(max_length=100)),
                ('board', models.CharField(blank=True, choices=[('RBSE', 'RBSE'), ('CBSE', 'CBSE')], default='RBSE', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schoolcreatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_no', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentcreatedby', to=settings.AUTH_USER_MODEL)),
                ('classname', models.ManyToManyField(related_name='classename', to='education.classsection')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('first', models.SmallIntegerField(blank=True, null=True)),
                ('second', models.SmallIntegerField(blank=True, null=True)),
                ('third', models.SmallIntegerField(blank=True, null=True)),
                ('total', models.SmallIntegerField(blank=True, default='calculate_total', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectmarkcreatedby', to=settings.AUTH_USER_MODEL)),
                ('classname', models.ManyToManyField(related_name='myclassename', to='education.classsection')),
                ('subject', models.ManyToManyField(related_name='marksubjects', to='education.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('joining_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachercreatedby', to=settings.AUTH_USER_MODEL)),
                ('classname', models.ManyToManyField(related_name='classenames', to='education.classsection')),
                ('subject', models.ManyToManyField(related_name='subjects', to='education.subject')),
            ],
        ),
    ]
