# Generated by Django 6.1 on 2026-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='randomid',
            field=models.BigIntegerField(default=55),
            preserve_default=False,
        ),
    ]
