# Generated by Django 6.1 on 2026-08-24 14:02

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_product_randomid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('biginteger', models.BigIntegerField()),
                ('binary', models.BinaryField()),
                ('boolean', models.BooleanField()),
                ('pk', models.CompositePrimaryKey('decimal', 'integer', blank=True, editable=False, primary_key=True, serialize=False)),
                ('char', models.CharField()),
                ('date', models.DateField()),
                ('decimal', models.DecimalField()),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='')),
                ('file_path', models.FilePathField()),
                ('float', models.FloatField()),
                ('generated_field', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('decimal'), '*', models.F('float')), output_field=models.FloatField())),
                ('generic_ip_address', models.GenericIPAddressField()),
                ('image', models.ImageField(upload_to='')),
                ('integer', models.IntegerField()),
                ('json', models.JSONField()),
            ],
        ),
    ]
