# Generated by Django 6.1 on 2026-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='pk',
        ),
        migrations.AddField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
