# Generated by Django 6.1 on 2026-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_remove_sample_pk_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='decimal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
