# Generated by Django 6.1 on 2026-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_alter_sample_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='file_path',
            field=models.FilePathField(path='F:/srijan/bids'),
        ),
    ]
