# Generated by Django 6.1 on 2026-08-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 8, 26, 8, 44, 1, 454551, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
