# Generated by Django 6.1 on 2026-08-28 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0002_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 8, 28, 11, 31, 25, 521076, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
