# Generated by Django 6.1 on 2026-08-28 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0003_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 8, 28, 12, 23, 7, 70714, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
