# Generated by Django 6.1 on 2026-09-08 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0010_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 9, 8, 16, 20, 25, 690357, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
