# Generated by Django 6.1 on 2026-09-15 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localservices', '0013_alter_serviceprovider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 9, 15, 15, 0, 4, 958088, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
