# Generated by Django 6.1 on 2026-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='volume',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
