# Generated by Django 6.1 on 2026-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_donation_volume_requestt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentt',
        ),
        migrations.AddField(
            model_name='donation',
            name='blood_group',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
