# Generated by Django 6.1 on 2026-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_delete_commentt_donation_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
    ]
