# Generated by Django 6.1 on 2026-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_donor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
    ]
