# Generated by Django 6.1 on 2026-08-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_alter_donor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='blood_group',
            field=models.CharField(blank=True, null=True),
        ),
    ]
