# Generated by Django 6.1 on 2026-09-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_utilitycategory_utility'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utility',
            table='utilities_utilities',
        ),
        migrations.AlterModelTable(
            name='utilitycategory',
            table='utilities_utility_category',
        ),
    ]
