# Generated by Django 6.1 on 2026-09-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_alter_utility_table_alter_utilitycategory_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilityList',
        ),
        migrations.AlterModelTable(
            name='utility',
            table=None,
        ),
        migrations.AlterModelTable(
            name='utilitycategory',
            table=None,
        ),
    ]
