# Generated by Django 6.1 on 2026-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_delete_utilitylist_alter_utility_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='address',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='designation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='district',
            field=models.CharField(blank=True, default='Rajsamand', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='division',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='extrainfo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='state',
            field=models.CharField(blank=True, default='Rajasthan', help_text='State name in English', max_length=255, null=True),
        ),
    ]
