# Generated by Django 6.1 on 2026-09-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_utility_address_utility_designation_utility_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.utilitycategory'),
        ),
    ]
