# Generated by Django 6.1 on 2026-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_alter_utility_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='name_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
