# Generated by Django 6.1 on 2026-09-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_delete_venue'),
        ('utilities', '0007_alter_utility_name_en_alter_utility_name_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tehsil'),
        ),
    ]
